; The `ow` shim, and putting it on PATH (plan 10.1).
;
; `adr:0013-the-project-directory-is-the-unit` makes `ow` in a directory the
; way a project is opened — "the way `code .` does". That only works if `ow`
; is on PATH, so the installer is what puts it there; an application the user
; has to add to PATH by hand is an application whose main entrance is
; undocumented.
;
; The shim is a `.cmd` rather than a copy of the exe because it has to do two
; different things: with no arguments it opens the application scoped to the
; current directory, and with a subcommand it runs headless (9.2).

!macro customInstall
  ; A one-line launcher beside the application.
  FileOpen $0 "$INSTDIR\ow.cmd" w
  FileWrite $0 "@echo off$\r$\n"
  FileWrite $0 "rem open-wiki launcher. Generated by the installer; do not edit.$\r$\n"
  FileWrite $0 'if "%~1"=="" ($\r$\n'
  FileWrite $0 '  start "" "%~dp0open-wiki.exe" --project "%CD%"$\r$\n'
  FileWrite $0 ") else ($\r$\n"
  FileWrite $0 '  "%~dp0resources\app.asar.unpacked\ow.mjs" %*$\r$\n'
  FileWrite $0 ")$\r$\n"
  FileClose $0

  ; Per-user PATH, because the installer is per-user (`nsis.perMachine: false`).
  ; `EnVar` writes the registry value and broadcasts the change, so a shell
  ; opened after the install sees it without a reboot.
  EnVar::SetHKCU
  EnVar::AddValue "PATH" "$INSTDIR"
  Pop $0
!macroend

!macro customUnInstall
  EnVar::SetHKCU
  EnVar::DeleteValue "PATH" "$INSTDIR"
  Pop $0
  Delete "$INSTDIR\ow.cmd"
!macroend
