; The `ow` shim, and putting it on PATH (plan 10.1).
;
; `adr:0013-the-project-directory-is-the-unit` makes `ow` in a directory the
; way a project is opened — "the way `code .` does". That only works if `ow`
; is on PATH, so the installer is what puts it there; an application the user
; has to add to PATH by hand is an application whose main entrance is
; undocumented.
;
; The shim is a `.cmd` rather than a copy of the exe because it has to do two
; different things: with no arguments it opens the application scoped to the
; current directory, and with a subcommand it runs headless (9.2).
;
; **The headless branch runs the CLI bundle through Electron, not through
; node.** `ELECTRON_RUN_AS_NODE=1` makes `open-wiki.exe` a plain Node process,
; which is the only Node the installer can count on: 10.1 is "no external
; dependency to install", and Windows ships neither node nor a `.mjs` file
; association for one to be invoked through.
;
; **The no-argument branch passes no `--project`.** `start` hands the new
; process the shell's working directory, and the application already decides
; from that — counting it "only if it already looks like a project", which is
; what makes `ow` in a download folder open the launcher of 8.4 rather than
; treating that folder as a wiki. Passing `--project "%CD%"` overrode exactly
; that test, and quoting `%CD%` at a drive root broke besides.
;
; **Only headers NSIS itself ships are used.** An installer that depends on a
; plugin being present in whichever NSIS electron-builder downloads fails at
; `makensis` on a machine that is not this one, and the packaging run is the
; only place that would ever find out.

!include "WordFunc.nsh"
!include "WinMessages.nsh"

!macro customInstall
  ; The shim goes in its own directory, and only the shim goes there. That
  ; directory is what lands on PATH, so nothing else in the installation can be
  ; shadowed by a file dropped beside it — $INSTDIR is under %LOCALAPPDATA%,
  ; is writable by any process running as this user, and the user chose it.
  CreateDirectory "$INSTDIR\bin"
  FileOpen $0 "$INSTDIR\bin\ow.cmd" w
  FileWrite $0 "@echo off$\r$\n"
  FileWrite $0 "rem open-wiki launcher. Generated by the installer; do not edit.$\r$\n"
  FileWrite $0 "setlocal$\r$\n"
  FileWrite $0 'if not "%~1"=="" goto :headless$\r$\n'
  FileWrite $0 'start "" "%~dp0..\open-wiki.exe"$\r$\n'
  FileWrite $0 "goto :eof$\r$\n"
  FileWrite $0 ":headless$\r$\n"
  FileWrite $0 'set "ELECTRON_RUN_AS_NODE=1"$\r$\n'
  FileWrite $0 '"%~dp0..\open-wiki.exe" "%~dp0..\resources\ow.mjs" %*$\r$\n'
  FileClose $0

  ; Per-user PATH, because the installer is per-user (`nsis.perMachine: false`).
  ; `WordAdd` with `+` appends only when it is not already there, so reinstalling
  ; does not grow the variable; the broadcast is what lets a shell opened after
  ; the install see it without a reboot.
  ReadRegStr $0 HKCU "Environment" "PATH"
  ${WordAdd} "$0" ";" "+$INSTDIR\bin" $1
  WriteRegExpandStr HKCU "Environment" "PATH" "$1"
  SendMessage ${HWND_BROADCAST} ${WM_SETTINGCHANGE} 0 "STR:Environment" /TIMEOUT=5000
!macroend

!macro customUnInstall
  ReadRegStr $0 HKCU "Environment" "PATH"
  ${WordAdd} "$0" ";" "-$INSTDIR\bin" $1
  WriteRegExpandStr HKCU "Environment" "PATH" "$1"
  SendMessage ${HWND_BROADCAST} ${WM_SETTINGCHANGE} 0 "STR:Environment" /TIMEOUT=5000
  Delete "$INSTDIR\bin\ow.cmd"
  RMDir "$INSTDIR\bin"
!macroend
